### ISSUE TITLE
Consider using DOMPurify to sanitize HTML?

### ISSUE THREAD

**Issue by iarinormanno** [badoge/chat.vote#6]
Do you think this can be a problem?
I looked in the js files and saw purify but I don't think it should work that way

![image](https://github.com/badoge/chat.vote/assets/48630736/d516bf65-3f6b-46b4-b2ca-a2bb5db5b419)

**Comment by badoge** [comment]
The options that you add using the input on the site are not sanitized 
only the chat suggestions are sanitized

**Comment by iarinormanno** [comment]
oh, thank you
