### ISSUE TITLE
(Feature Request) Duplicate checker

### ISSUE THREAD

**Issue by PsycloneTM** [badoge/chat.vote#7]
A setting to turn on so you can't get duplicate links.

**Comment by badoge** [comment]
Can you provide more details? which page are you talking about?
The main page and the playlist page both don't allow duplicates

**Comment by PsycloneTM** [comment]
> Can you provide more details? which page are you talking about? The main page and the playlist page both don't allow duplicates

So they don't allow duplicate clips?

**Comment by badoge** [comment]
Yes, if 2 users request the same link they will be both mentioned in the request 
![image](https://github.com/badoge/chat.vote/assets/18620902/b6fa6297-4553-4957-b053-356b1b5e7899)

**Comment by PsycloneTM** [comment]
> Yes, if 2 users request the same link they will be both mentioned in the request ![image](https://private-user-images.githubusercontent.com/18620902/313824347-b6fa6297-4553-4957-b053-356b1b5e7899.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3OTM2MjMsIm5iZiI6MTcxMDc5MzMyMywicGF0aCI6Ii8xODYyMDkwMi8zMTM4MjQzNDctYjZmYTYyOTctNDU1My00OTU3LWIwNTMtMzU2YjFiNWU3ODk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDIwMjIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyYTg3MjJmNzZiZjZiZjBmY2IzNzA2YzZjMjNhYzZkMWZlM2VmZGY3N2YwZGUyNmMwZjMxMDcxNjMxNGVkNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wstqk_3xZsDG52kvg1RsOoRBUoWWbd4LAOkATFdnBR4)

Oh ok cool thanks will kick clips ever be supported?

**Comment by badoge** [comment]
never :)

**Comment by PsycloneTM** [comment]
> never :)

even if forsen moves to kick?

**Comment by badoge** [comment]
we'll see we'll see the winner gets tea
